### ISSUE TITLE
The SLI Plugin window does not work from version 9.02.9 onwards

### ISSUE THREAD

**Issue by MARVINALIEN** [simelation/simhub-plugins#19]
**Describe the bug**
SLI Plugin from version 9.02.9 cannot be configured because it does not show windows even if it seems to work in game. The problem is present from version 9.02.9 to the latest 9.02.12. Going back to version 9.02.8 the plugin window works correctly.

**Simhub version**
9.02.9 - 9.02.10 -9.02.11 9.02.12

**To Reproduce**

1 start simhub
2 enter SLI Plugin
3 Empty window

**Expected behavior**
the usual window shown up to version 9.02.08

**Screenshots**
![9 2 9 bug](https://github.com/SHWotever/SimHub/assets/168651411/e511e799-07e6-4d9b-865b-d9548334b77c)

![9 2 8 ok](https://github.com/SHWotever/SimHub/assets/168651411/7a780f12-6f59-42c2-bc04-1c8dcde6f4dd)

**Log files**
[Logs.zip](https://github.com/SHWotever/SimHub/files/15177765/Logs.zip)

**Comment by lukester1975** [comment]
Weird, I wonder what changed in a patch release to cause that... I'll try to find some time to look at it over the weekend.

Thanks for the report (and for figuring out which version it started from)!

**Comment by MARVINALIEN** [comment]
I think it was right to provide you with the right information to make the solution easier for you, this is the opportunity to thank you for sharing this plugin and for the next update.

**Comment by lukester1975** [comment]
I think this should fix it: https://github.com/simelation/simhub-plugins/releases/download/%40simelation%2Fsimhub-sli-plugin%400.11.2/simelation-simhub-sli-plugin-v0.11.2.tgz

**Comment by MARVINALIEN** [comment]
Great, this new version is ok, also tested with today's release SimHub 9.2.14 .
Thanks for your time
![9 2 14 ok](https://github.com/simelation/simhub-plugins/assets/168651411/2daab8d8-73c9-418d-9b28-536373a3f42c)

**Comment by lukester1975** [comment]
Excellent. Cheers.
