### ISSUE TITLE
SIM Race Deluxe Display

### ISSUE THREAD

**Issue by klarafall42** [simelation/simhub-plugins#21]
Hi there,
is there any chance of getting SIM Race Deluxe USB Display to work with this plugin in the future? Would love to use my rotary switches as the SLI-Pro-Displays do. It quite the same device. Maybe it is possible.
![9491405208_435cff1f1c_b-2178134359](https://github.com/simelation/simhub-plugins/assets/171837609/d8ec154b-7232-42f9-80e5-1548562bc85f)

**Comment by lukester1975** [comment]
Probably not by me, sorry.

If you're not a programmer yourself, maybe it's an opportunity to try 😀 Or if you've got a local programmer friend you can lend the device to and persuade they want to spend some time sniffing USB packets with Wireshark...

Good luck!
